Bug/gouri-panda/2331 file reader injected in other class than normally
kiwix/kiwix-android pull request #2571
Opened 2021-01-07 14:31 UTC by gouri-panda

Fixes #2331

2021-01-07 17:47 UTC, abdulwd commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt
> +} catch (e: Exception) {
Why not IOException?

2021-01-07 17:50 UTC, gouri-panda commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt
> +} catch (e: Exception) {
ok

2021-01-07 23:50 UTC, gouri-panda commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt
>  package org.kiwix.kiwixmobile.core.main
@s-ayush2903 Thanks for the advice!

2021-01-07 23:50 UTC, gouri-panda commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt
> +  this.assets.open(filePath)
Sorry! Old java habit.

2021-01-09 20:46 UTC, mhutti1 requested changes

2021-01-09 20:46 UTC, mhutti1 commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
> +import java.io.FileReader;
Why is this import needed?

2021-01-11 20:38 UTC, mhutti1 approved these changes

2021-01-11 20:38 UTC, merged