Fix Initial download doesn't happen
kiwix/kiwix-android pull request #3084
Opened 2022-09-20 13:14 UTC by MohitMaliFtechiz

Fixes: #3080

2022-09-21 10:01 UTC, gouri-panda requested changes
We should add tests as well.

2022-09-21 11:53 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz It also fails on android 30.

hi @gouri-panda 
just re-run the job and android 30 test passed.

2022-09-22 11:49 UTC, MohitMaliFtechiz commented
> We should add tests as well.

Hi @gouri-panda , i have added test case for this scenario and now it's ready for review.

2022-09-26 13:50 UTC, gouri-panda approved these changes

2022-09-26 14:45 UTC, merged