Localisation updates from https://translatewiki.net.
kiwix/kiwix-android pull request #3144
Opened 2022-12-05 12:05 UTC by translatewiki

Translation updates

2023-01-26 05:54 UTC, kelson42 commented
@MohitMaliDeveloper Why have you fixed something manually here? This is « forbidden »!

2023-01-27 05:40 UTC, MohitMaliFtechiz commented
> @MohitMaliDeveloper Why have you fixed something manually here? This is « forbidden »!

@kelson42  I just did so that atleast in a month translate wiki changes were merged . But yes onces changes are done on upstream we do not required to do this.

2023-01-27 05:47 UTC, kelson42 commented
@MohitMaliFtechiz Does that mean you have still modifications made on TW waiting approval since two weeks?

2023-01-27 05:52 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz Does that mean you have still modifications made on TW waiting approval since two weeks?

Yes one changes are left to be approved there.

2023-01-27 05:56 UTC, kelson42 commented
@MohitMaliFtechiz Ok, we are not in a hurry, but if it takes months, this is going to be a problem. Please wait a bit, and if nothing happens you should write a message on TW to one of rhe other active translators in this language to explicitly request their help to validate your modification.

2023-03-03 11:44 UTC, kelson42 commented
@MohitMaliDeveloper Any news here? Are we OK now with TW (all the tickets have been closed)? Can we merge (still without modifying manually the PR)? If "not" please open corresponding bug tickets.

2023-03-06 17:45 UTC, kelson42 commented
@MohitMaliFtechiz why I don’t have a feedback after 3 days? As a reminder: handling already open PR is PRIO1.

2023-03-23 13:29 UTC, kelson42 commented
@MohitMaliFtechiz good i will check all of this later.

2023-03-24 14:47 UTC, kelson42 requested changes
Still NOK, I´m out of patience.

2023-03-24 14:47 UTC, kelson42 commented on core/src/main/res/values-fr/strings.xml
> +  <string name="crash_title">Hé bien.... c’est embarrassant.</string>
@MohitMaliFtechiz No reason to have `....` when in the original this is `...`

2023-03-24 15:11 UTC, kelson42 commented on core/src/main/res/values-fr/strings.xml
> +  <string name="crash_title">Hé bien.... c’est embarrassant.</string>
This is wrong and should be changed upstream in TW

2023-03-24 15:13 UTC, merged