Fixed Hosted Books don't update on Application
kiwix/kiwix-android pull request #3218
Opened 2023-01-27 09:55 UTC by MohitMaliFtechiz

Fixes #2537 

**Whats the issue**
We are not updating ```Adapter item``` after server is started.

**How i fix this**
* I have store all books in a single list (which we required after server closed).
* I have updated ```AdapterItems``` with only selected zim files, when server start.
* After closing the server, i have updated ```AdapterItems``` with all books list (so all the books is visible to user).

https://user-images.githubusercontent.com/34593983/215057754-d2554e73-0f39-4374-8dfa-b01aa8a1f922.mp4

2023-01-27 10:44 UTC, kelson42 commented
@MohitMaliDeveloper We do agree that this is absolutly unecessary if #3219 is implemented?

2023-01-27 10:58 UTC, kelson42 commented
@MohitMaliDeveloper #3219 should be implemented, this was the solution, not this. I can not figure out why you did this although i have proposed #3219 (a new ticket was not necessary as we already have a bug ticket).

2023-01-27 11:10 UTC, MohitMaliFtechiz commented
> @MohitMaliDeveloper #3219 should be implemented, this was the solution, not this. I can not figure out why you did this although i have proposed #3219 (a new ticket was not necessary as we already have a bug ticket).

hi @kelson42 ,

I have created separate ticket because there was changes on the UI so just to make sure we have direct reference to changes.

2023-01-27 11:11 UTC, MohitMaliFtechiz commented
Solutions placed in  https://github.com/kiwix/kiwix-android/issues/3219

2023-01-27 18:20 UTC, kelson42 commented
OK for me, @gouri-panda This is on you now for the revirw.

2023-01-31 09:35 UTC, gouri-panda commented
@MohitMaliFtechiz #3219 has already close. Why are you mentioning that it closes that issue?

2023-01-31 11:03 UTC, kelson42 commented
@gouri-panda ticket chaos, forget about it.

2023-01-31 11:10 UTC, gouri-panda commented
@kelson42 Ok

2023-02-02 11:58 UTC, gouri-panda reviewed
@MohitMaliDeveloper The update items still don't update after the server starts and the server crashes if the app goes in the background or switches to another application.

2023-02-02 11:58 UTC, gouri-panda requested changes
@MohitMaliDeveloper The update items still don't update after the server starts and the server crashes if the app goes in the background or switches to another application.

2023-02-02 12:53 UTC, MohitMaliFtechiz commented
> @MohitMaliDeveloper The update items still don't update after the server starts and the server crashes if the app goes in the background or switches to another application.

@gouri-panda , 
I have some questions
* is this server crash is different from https://github.com/kiwix/kiwix-android/issues/3118 ?.
* Your mobile connected with WiFi or mobile network?
* If you connected with WiFi and mobile internet is also on, then please turn off the mobile internet and only try with WiFi (for this case, i had faced this problem with server).

2023-02-02 16:56 UTC, gouri-panda commented
>is this server crash is different from https://github.com/kiwix/kiwix-android/issues/3118 ?.

No, it is completely different. In this case, the if the app goes to the background and if refresh the page after sometime it stops it crashes.
>Your mobile connected with WiFi or mobile network?

Mobile Network.
>If you connected with WiFi and mobile internet is also on, then please turn off the mobile internet and only try with WiFi (for this case, i had faced this problem with server).

No, I was not connected to WIFI. But if you face that problem also that isn't idol case. We should work on that too.

Also, I found a small memory leak. It's happening because we are forgetting to unbind some services in the ZimHostFragment.

2023-02-06 10:12 UTC, MohitMaliFtechiz commented
hi @gouri-panda ,
* I have tested this again in both scenario (WIFI and mobile network) and it's working fine.
* I'm attaching both video

**WIFI**


https://user-images.githubusercontent.com/34593983/216944505-8761c864-c185-4073-a504-a3d4c3cdf613.mp4



**Mobile Network**

https://user-images.githubusercontent.com/34593983/216943420-3d0f63e5-4bfb-48fe-b135-0968527a9856.mp4

2023-02-06 10:48 UTC, MohitMaliFtechiz commented
>  Also, I found a small memory leak. It's happening because we are forgetting to unbind some services in the ZimHostFragment.

@gouri-panda , can you please provide the logs?

2023-02-13 05:01 UTC, kelson42 commented
@gouri-panda any feedback?

2023-02-13 08:51 UTC, gouri-panda commented
@MohitMaliDeveloper @kelson42 Sorry for the late reply. Here are the logs
<details><summary> Logs </summary>

```

StrictMode policy violation; ~duration=24 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:249)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:478)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
                                                                                                    	at java.io.FileWriter.<init>(FileWriter.java:90)
                                                                                                    	at com.android.server.am.OomAdjuster.updataKernelTopUid(OomAdjuster.java:2178)
                                                                                                    	at com.android.server.am.OomAdjuster.computeOomAdjLocked(OomAdjuster.java:2065)
                                                                                                    	at com.android.server.am.OomAdjuster.updateOomAdjLocked(OomAdjuster.java:344)
                                                                                                    	at com.android.server.am.OomAdjuster.updateOomAdjLocked(OomAdjuster.java:423)
                                                                                                    	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19440)
                                                                                                    	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2309)
                                                                                                    	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:16199)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2645)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3168)
                                                                                                    	at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:169)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1161)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1130)
                                                                                                    # via Binder call with stack:
                                                                                                    	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2358)
                                                                                                    	at android.os.Parcel.readExceptionCode(Parcel.java:2334)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2295)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.bindIsolatedService(IActivityManager.java:6130)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy2.bindIsolatedService(Unknown Source)
                                                                                                    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1888)
                                                                                                    	at android.app.ContextImpl.bindService(ContextImpl.java:1804)
                                                                                                    	at android.content.ContextWrapper.bindService(ContextWrapper.java:766)
                                                                                                    	at android.content.ContextWrapper.bindService(ContextWrapper.java:766)
                                                                                                    	at org.kiwix.kiwixmobile.webserver.ZimHostFragment.bindService(ZimHostFragment.kt:285)
                                                                                                    	at org.kiwix.kiwixmobile.webserver.ZimHostFragment.onStart(ZimHostFragment.kt:276)
                                                                                                    	at androidx.fragment.app.Fragment.performStart(Fragment.java:3162)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2902)
                                                                                                    	at androidx.fragment.app.Fragment.performStart(Fragment.java:3171)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.Fr [...]

2023-02-13 09:44 UTC, MohitMaliFtechiz commented
hi @gouri-panda , this is not the memory leak, it's ```StrictMode disk violation``` warning. it's device and android versions specific, below android 10 this error not happen but above android 10 it's happen, when we read any data from storage. I guess you are using above android 10 device.

We can avoid this by using ```permitDiskWrites()``` method of ```StrictMode.ThreadPolicy.Builder()``` .

2023-02-13 09:47 UTC, gouri-panda commented
@MohitMaliFtechiz But it still crashes the App. Have you tried successfully reproduce the crash?

2023-02-13 09:51 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz But it still crashes the App. Have you tried successfully reproduce the crash?

@gouri-panda , I'm unable to reproduce this crash. it's working fine in my device (I have checked on multiple devices like in Samsung , Vivo , Redmi).

2023-02-13 09:52 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz But it still crashes the App. Have you tried successfully reproduce the crash?

@gouri-panda , I'm unable to reproduce this crash. it's working fine in my device (I have checked on multiple devices like in Samsung , Vivo , Redmi).

2023-02-13 09:56 UTC, gouri-panda commented
@MohitMaliFtechiz Ok . I'll send the video of a crash in slack.

2023-02-13 09:59 UTC, MohitMaliFtechiz commented
@gouri-panda , OK

2023-03-03 11:16 UTC, kelson42 commented
@MohitMaliDeveloper @gouri-panda What is the status here? What are the next steps?

2023-03-03 11:31 UTC, MohitMaliFtechiz commented
@kelson42 , i have reproduce the bug after retying @gouri-panda steps many times
it's giving fatal signal error, fatal signal error occurs when we have crash on library side. we have a ticket open with same error logs #3118. Logs are not enough to identify the exact problem (what is the main problem of crash).
error logs.
 ```
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 32087 (MHD-single), pid 30676 (wix.kiwixmobile)
```
@gouri-panda , have you find something how we can tackle this situation?

2023-03-03 13:52 UTC, gouri-panda commented
@MohitMaliDeveloper Unfortunately no! But it is vital to solve this problem here or in another ticket.

cc @kelson42

2023-03-06 17:43 UTC, kelson42 commented
@gouri-panda I guess the situation/bug is not worse than without this PR?

2023-03-06 19:05 UTC, gouri-panda commented
>@gouri-panda I guess the situation/bug is not worse than without this PR?

@kelson42 I believe this bug exists with this PR.

2023-03-06 19:39 UTC, kelson42 commented
@MohitMaliFtechiz This looks like a regression you have added, we can not merge this like this. Please identifiy clearly what is going on. This might not be what you believe it is.

2023-03-09 12:01 UTC, MohitMaliFtechiz commented
@kelson42 , @gouri-panda  , I'm re-testing this to reproduce this error and i'm stuck in a loop (both ```develop``` and ```this branch code```). Server started but when i'm going to view books on the browser, server crashed every time (i have also try to clear the data of application even i have uninstall the application as well, invalidate cache and restart if any cache is kept by IDE, but that did not work here) **Device Redmi note 9, Samsung device both are running on android 12**.

@gouri-panda , can you please test it if you have a device of android 12 (is this error only occurred to me only).


**Better logs i have found**
```

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2d in tid 2501 (MHD-single), pid 32162 (wix.kiwixmobile)

Cmdline: org.kiwix.kiwixmobile
pid: 32162, tid: 2501, name: MHD-single  >>> org.kiwix.kiwixmobile <<<
#00 pc 00000000002c158c  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
#01 pc 00000000002c1aac  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
#02 pc 00000000002c1cb0  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
#03 pc 00000000002c2034  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
#04 pc 00000000002c246c  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so (kiwix::OPDSDumper::dumpOPDSFeed(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) const+140)
#05 pc 000000000030db94  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so (kiwix::InternalServer::handle_catalog(kiwix::RequestContext const&)+1088)
#06 pc 000000000030a1d8  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so (kiwix::InternalServer::handle_request(kiwix::RequestContext const&)+452)
#07 pc 0000000000309dfc  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so (kiwix::InternalServer::handlerCallback(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**)+512)
#08 pc 0000000000309bec  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
#09 pc 000000000076e52c  /data/app/~~DZlsTvX5bTPoYwvX687Jig==/org.kiwix.kiwixmobile-vAYcZjKt7fhZLg0Aea4ZGg==/base.apk!libkiwix.so
```

```
Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x754c227000 in tid 7970 (MHD-single), pid 6806 (wix.kiwixmobile)

Cmdline: org.kiwix.kiwixmobile
pid: 6806, tid: 7970, name: MHD-single  >>> org.kiwix.kiwixmobile <<<
#00 pc 00000000002f6798  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::urlEncode(std::string const&, bool)+112)
#01 pc 00000000002c2f58  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::OPDSDumper::categoriesOPDSFeed() const+160)
#02 pc 00000000003233d4  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::InternalServer::handle_catalog_v2_categories(kiwix::RequestContext const&)+84)
#03 pc 000000000032297c  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::InternalServer::handle_catalog_v2(kiwix::RequestContext const&)+828)
#04 pc 000000000030d874  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::InternalServer::handle_catalog(kiwix::RequestContext const&)+288)
#05 pc 000000000030a1d8  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::InternalServer::handle_request(kiwix::RequestContext const&)+452)
#06 pc 0000000000309dfc  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so (kiwix::InternalServer::handlerCallback(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**)+512)
#07 pc 0000000000309bec  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so
#08 pc 000000000076e52c  /data/app/~~oYdXkPYFXsF8MBIRv4MJgQ==/org.kiwix.kiwixmobile-U1vh83JA5KupbSNVCffmtQ==/base.apk!libkiwix.so

```

**Develop branch**


https://user-images.githubusercontent.com/34593983/223997498-a4cf9105-b500-47c6-8831-49006d0d6036.mp4


**This PR code**

https://user-images.githubusercontent.com/34593983/223997944-621e3370-ce56-42a8-91e4-3eaa93951493.mp4


then i have tested it in android 11 and it's works in android 11 (it is not going into crash loop).

> I can't reproduce with the develop branch.

@gouri-panda , the only change in this PR and in develop is, when user select any zim file then we are restarting the server (if already started).

2023-04-24 13:28 UTC, MohitMaliFtechiz commented
@kelson42 @gouri-panda , I have re-access this ticket and found when I am starting the server in my `Android 12` device(upgraded from `Android 11`) it hangs for 12 seconds while adding the books into the library, and after that, it crashes. But in `Android 11` it is working fine.
* This issue I am only facing this with Redmi devices, for other manufacturers the code is working well (I have tested with `Samsung`, `Google Pixel 6A` and `Vivo` devices). This problem I have only faced above android 11 in `Redmi devices`, I have tested it in `Redmi 6A` (which runs on `android 9`) and it is working normally.

```
W/MIUIScout App:  (Current message: duration=5004ms seq=242 late=2ms h=android.app.ActivityThread$H w=115)
W/MIUIScout App: Event:APP_SCOUT_HANG Thread:main backtrace:
        at org.kiwix.kiwixlib.Library.addBook(Native Method)
        at org.kiwix.kiwixmobile.webserver.KiwixServer$Factory.createKiwixServer(KiwixServer.kt:36)
        at org.kiwix.kiwixmobile.webserver.WebServerHelper.startKiwixServer(WebServerHelper.kt:79)
        at org.kiwix.kiwixmobile.webserver.WebServerHelper.startAndroidWebServer(WebServerHelper.kt:69)
        at org.kiwix.kiwixmobile.webserver.WebServerHelper.startServerHelper(WebServerHelper.kt:50)
        at org.kiwix.kiwixmobile.webserver.wifi_hotspot.HotspotService.onStartCommand(HotspotService.kt:79)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4808)
        at android.app.ActivityThread.access$2200(ActivityThread.java:275)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8280)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
I/wix.kiwixmobil: Thread[6,tid=9600,WaitingInMainSignalCatcherLoop,Thread*=0xb400007637040000,peer=0x165805c8,"Signal Catcher"]: reacting to signal 3
```

2023-04-24 21:29 UTC, gouri-panda commented
>his issue I am only facing this with Redmi devices, for other manufacturers the code is working well (I have tested with Samsung, Google Pixel 6A and Vivo devices). This problem I have only faced above android 11 in Redmi devices

@MohitMaliDeveloper Yes, I have a problem with this device. So, basically, you are saying with only Redmi with android 11 has this issue.

> it  hangs for 12 seconds while adding the books into the library, and after that, it crashes. 

I think this is the problem we should solve in order to fix the issue. Should we create another ticket for this or should we solve it here? This PR is taking so long. Sorry for the late response to your previous comments.

2023-04-25 08:40 UTC, MohitMaliFtechiz commented
> I think this is the problem we should solve in order to fix the issue. Should we create another ticket for this or should we solve it here? This PR is taking so long. Sorry for the late response to your previous comments.


We should fix this here the main error is `APP_SCOUT_HANG`, I'm trying to find a way to fix this.

2023-04-25 13:05 UTC, MohitMaliFtechiz commented
@gouri-panda , I have found the clue, when the books are loading on the server then this crash happened (the main error is `null pointer dereference`), so it means there is an error on the library side. I have tested it on 2 Redmi devices (`Redmi k20i` and `Redmi note9` both running on `Android 12`) the server crashed `8/10` times and in `Google Pixel 6a` server is not crashed(I have tried almost 20-30 times).

So IMO there is any method in the library while loading the content on the server which is conflicting or blocking the `MIUI Code` which is the cause of the crash.

<img src="https://user-images.githubusercontent.com/34593983/234281237-74fad171-2f13-42c1-8e71-dc0cb9fc0a70.JPEG" width="200" height="400" />


**here are the logs.**
```
Free pages count per migrate type at order       0      1      2      3      4      5      6      7      8      9     10 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type    Unmovable      1      6    293   1011     80      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type      Movable      0      1      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type  Reclaimable     10      7      1     10      2      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type   HighAtomic     21     18     10     13      7      2      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone    DMA32, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type    Unmovable    592    413     29    180     30      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type      Movable    617     18      5      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type  Reclaimable     54     86      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type          CMA     71      1      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type   HighAtomic     22     53     17      2     10      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  Node    0, zone   Normal, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
2023-04-25 18:00:22.279   908-909   vendor.xia....0-service ven...omi.hardware.mimd@1.0-service  E  memory info -------------end
** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
Build fingerprint: 'Redmi/xagain/xagain:12/SP1A.210812.016/V13.0.3.0.SLOINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-04-25 18:00:21.923805769+0530
Process uptime: 0s
Cmdline: org.kiwix.kiwixmobile
pid: 32295, tid: 449, name: MHD-single  >>> org.kiwix.kiwixmobile <<<
uid: 10261
tagged_addr_ctrl: 0000000000000001
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8

-------------------------------------------
Cause: null pointer dereference

x0  b40000739e840d50  x1  0000000000000008  x2  00000072e9b96b00  x3  00000072e9b96b00
x4  0000000000000000  x5  b4000072bb0dccbc  x6  0000000000000065  x7  0000000000000067
x8  00000000000000b4  x9  ff7d600e0ded9c50  x10 0000000000000001  x11 00000072b172267c
x12 0000000000000000  x13 0000000000597bb8  x14 00000000ffffffbd  x15 5555555555555556
x16 00000074425d9d50  x17 00000074425c98ec  x18 000000000000008f  x19 b40000739e840d50
x20 b40000739e840d48  x21 00000072e9a193e8  x22 b40000739e840d50  x23 b40000739e840da0
x24 b4000072b9844000  x25 000000739f2b9b60  x26 000000739f2b9b58  x27 0000000000000008
x28 0000000000000000  x29 000000739f2b9090
lr  00000072e968defc  sp  000000739f2b9090  pc  00000072e968e814  pst 0000000000001000
backtrace:
#00 pc 0000000000607814  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so
#01 pc 0000000000606ef8  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (Xapian::Database::Database(Xapian::Database const&)+60)
#02 pc 0000000000612d48  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (Xapian::Enquire::Internal::Internal(Xapian::Database const&)+48)
#03 pc 0000000000612fac  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (Xapian::Enquire::Enquire(Xapian::Database const&)+36)
#04 pc 00000000002a84d8  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::Library::filterViaBookDB(kiwix::Filter const&) const+120)
#05 pc 00000000002a86b0  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::Library::filter(kiwix::Filter const&) const+48)
#06 pc 000000000030e508  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::InternalServer::search_catalog(kiwix::RequestContext const&, kiwix::OPDSDumper&)+176)
#07 pc 000000000030db14  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::InternalServer::handle_catalog(kiwix::RequestContext const&)+960)
#08 pc 000000000030a1d8  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::InternalServer::handle_request(kiwix::RequestContext const&)+452)
#09 pc 0000000000309dfc  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so (kiwix::InternalServer::handlerCallback(MHD_Connection, char const, char const, char const, char const, unsigned long, void**)+512)
#10 pc 0000000000309bec  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so
 #11 pc 000000000076e52c  /data/app/~~YS2pAeHFqcJadTHNomQVgA==/org.kiwix.kiwixmobile-ii4dlQ9ZKxIEkmTVNGVM6w==/base.apk!libkiwix.so
2023-04-25 18:00:22.305  2370-2989  d                       com.miui.securitycenter.remote       V  flags=16
```

2023-04-25 19:55 UTC, kelson42 commented
IMO, it does not make sense to continue here as long as we don’t use latest libkiwix. This would be a waste of time probably.

2023-08-16 11:02 UTC, kelson42 commented
@MohitMaliFtechiz what is the status here? Does this PR is still needed? Does ot depends an an other PR?

2023-08-16 11:27 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz what is the status here? Does this PR is still needed?

@kelson42, indeed, we still require this PR. It incorporates changes that keep the checkbox always visible, allowing users to update books without needing to close the server.

>  Does ot depends an an other PR?

@gouri-panda, I've thoroughly tested this PR alongside the changes in #3217 on various devices, such as `Google Pixel 6a`, `Redmi K20i`, and `Redmi Note9`. Previously, the server would crash on the Redmi Note9, but with the new wrapper, the server now functions smoothly on this device as well. The new wrapper has resolved previous library-related crashes.

Therefore, once we've successfully merged #3217, we can proceed with merging this PR.

2023-08-17 03:43 UTC, kelson42 commented
@MohitMaliDeveloper please rebase on `Issue#3216` in place of `develop` if #3217 is needed to get this PR working fine.

2023-08-17 06:32 UTC, MohitMaliFtechiz commented
> @MohitMaliDeveloper please rebase on `Issue#3216` in place of `develop` if #3217 is needed to get this PR working fine.

@kelson42 Done.

2023-08-19 08:54 UTC, kelson42 commented
@gouri-panda Does this PR (with the new wrapper) could have fixed #2683 by any chance?

2023-08-21 10:13 UTC, MohitMaliFtechiz commented
> @gouri-panda @MohitMaliDeveloper Does this PR (with the new wrapper) could have fixed https://github.com/kiwix/kiwix-android/issues/2683 by any chance?

@kelson42, @gouri-panda I have tried #2683 with this PR and now I am unable to reproduce the error, so it was probably the error on the libkiwix side which is fixed now in the new wrapper.

2023-08-24 18:31 UTC, gouri-panda commented
@kelson42 @MohitMaliDeveloper I've tried the recent version, and I didn't encounter the bugs that I had previously encountered. Maybe it's somewhere fixed. Don't know where, perhaps @MohitMaliDeveloper have a better idea. I'll start reviewing again.

2023-08-25 05:47 UTC, MohitMaliFtechiz commented
> @kelson42 @MohitMaliDeveloper I've tried the recent version, and I didn't encounter the bugs that I had previously encountered. Maybe it's somewhere fixed. Don't know where, perhaps @MohitMaliDeveloper have a better idea. I'll start reviewing again.

@gouri-panda Without the latest libkiwix, the bug still exists, The bug was somewhere in `libkiwix` itself because if we were trying to open the server again and again it crashed the application as shown here https://github.com/kiwix/kiwix-android/issues/3218#issuecomment-1461906396, but with the latest wrapper, the server functionality is now stable.

2023-09-22 05:28 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz Can we just close #2537 and this PR?

@kelson42 Yes we can close this PR and #2537 as we have implemented both functionalities in this PR and with the latest wrapper changes the server functionality is now stable, there is no crash which reported by the @gouri-panda in this PR. 

But we have some conflicts in this PR which I am resolving. After that @gouri-panda it would be a good idea to test the PR, whether the issue is resolved at your end or not.

2023-09-22 05:30 UTC, kelson42 commented
@gouri-panda said that he was not able to reprouce the bug, so why this PR?

2023-09-22 05:48 UTC, MohitMaliFtechiz commented
> @kelson42 @MohitMaliDeveloper I've tried the recent version, and I didn't encounter the bugs that I had previously encountered. Maybe it's somewhere fixed. Don't know where, perhaps @MohitMaliDeveloper have a better idea. I'll start reviewing again.

@kelson42, @gouri-panda was unable to reproduce the https://github.com/kiwix/kiwix-android/issues/2683.

> @gouri-panda said that he was not able to reproduce the bug, so why this PR?

In this PR we have implemented to always visible the checkbox functionality as you requested in https://github.com/kiwix/kiwix-android/issues/2537 for this functionality @gouri-panda panda sometimes faced the server crash issue, which is fixed with the latest wrapper.

2023-09-22 05:53 UTC, kelson42 commented
@MohitMaliFtechiz OK, so please rebase and make it ready to review

2023-09-22 06:41 UTC, MohitMaliFtechiz commented
@kelson42, @gouri-panda Now this PR is ready for re-review.

2023-09-23 14:57 UTC, gouri-panda requested changes
@MohitMaliFtechiz The server doesn't host any books at all. In fact, it is unable to load the website at all on my both Desktop and phone. Also, i encountered some memory leaks in the process. We should probably add tests to see if we host only selected items or not.

2023-09-23 15:34 UTC, kelson42 commented
We should probably have some kind od UI test here. At least to secure no memory leak in the process.

2023-09-25 09:22 UTC, MohitMaliFtechiz commented
> We should probably have some kind od UI test here. At least to secure no memory leak in the process.

We have `TopLevelDestinationTest` and some other UI tests that check for memory leaks in the application. In these test cases, we also testing the hosted screen.

I also observed sometimes my Redmi Note 9(Android 12) has some memory leak logs but when I debug those logs they indicate it's internal to Android classes. But with other Android 12 devices, there are no memory leaks. So it might be my device-related issue.



> I encountered some memory leaks in the process.

@gouri-panda Can you please share the logs of the memory leak? It would be helpful to debug the memory leak.

2023-09-25 10:08 UTC, gouri-panda commented
@MohitMaliDeveloper what I meant by UI test is the thing we fixed here meaning showing the application.  Here are the logs that'll be helpful.
<details><summary> Error Logs</summary>

```

 Process: org.kiwix.kiwixmobile, PID: 9831
                                                                                                    java.lang.RuntimeException: Unable to create application
                                                                                                    org.kiwix.kiwixmobile.KiwixApp: io.objectbox.exception.DbSchemaException: Incoming
                                                                                                    index ID 5:5193586130937114010 does not match existing UID
                                                                                                    710049454599478240
                                                                                                    	at
                                                                                                    android.app.ActivityThread.handleBindApplication(ActivityThread.java:7109)
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:259)
                                                                                                    	at
                                                                                                    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at
                                                                                                    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
                                                                                                    Caused by: io.objectbox.exception.DbSchemaException: Incoming index ID
                                                                                                    5:5193586130937114010 does not match existing UID 710049454599478240
                                                                                                    	at io.objectbox.BoxStore.nativeCreateWithFlatOptions(Native Method)
                                                                                                    	at io.objectbox.BoxStore.<init>(BoxStore.java:268)
                                                                                                    	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:548)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule.providesBoxStore(DatabaseModule.kt:45)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule_ProvidesBoxStoreFactory.providesBoxStore(DatabaseModule_ProvidesBoxStoreFactory.java:46)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule_ProvidesBoxStoreFactory.get(DatabaseModule_ProvidesBoxStoreFactory.java:37)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule_ProvidesBoxStoreFactory.get(DatabaseModule_ProvidesBoxStoreFactory.java:13)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule_ProvidesFetchDownloadDaoFactory.get(DatabaseModule_ProvidesFetchDownloadDaoFactory.java:41)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.DatabaseModule_ProvidesFetchDownloadDaoFactory.get(DatabaseModule_ProvidesFetchDownloadDaoFactory.java:14)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.downloader.fetch.FetchDownloadMonitor_Factory.get(FetchDownloadMonitor_Factory.java:36)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.downloader.fetch.FetchDownloadMonitor_Factory.get(FetchDownloadMonitor_Factory.java:12)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.ApplicationModule_ProvideDownloadMonitor$core_debugFactory.get(ApplicationModule_ProvideDownloadMonitor$core_debugFactory.java:37)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.modules.ApplicationModule_ProvideDownloadMonitor$core_debugFactory.get(ApplicationModule_ProvideDownloadMonitor$core_debugFactory.java:13)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at
                                                                                                    org.kiwix.kiwixmobile.core.di.components.DaggerCoreComponent$CoreComponentImpl.injectCoreApp(DaggerCoreComponent.java:654)
                                                                                                    	at
                                                                                                   [...]

2023-09-25 10:49 UTC, MohitMaliFtechiz commented
> @MohitMaliDeveloper what I meant by UI test is the thing we fixed here meaning showing the application. Here are the logs that'll be helpful.
> 
> Error Logs
> Memory Leaks
>  Record_2023-09-25-15-25-54.mp4

@gouri-panda Thanks for providing the complete information. I tested it with the Brave browser, and it is working perfectly on my device.


https://github.com/kiwix/kiwix-android/assets/34593983/8e37ac8b-1d18-4ac9-a86b-31121b10c7d1


The error logs are quite strange they are related to the object box and in this PR we don't have any changes related to the object box. Can you please try to install the fresh application on your device?

2023-09-25 14:07 UTC, kelson42 commented
If things are related to objectbox, we shoukd ignore IMO.

2023-09-26 10:26 UTC, kelson42 commented
@gouri-panda hopefully fix on api24 can fix your seldom memory leak, so we can merge finallt.

2023-09-26 15:04 UTC, MohitMaliFtechiz commented
@gouri-panda I have placed a fix for memory leak also added test cases as you requested.

2023-10-08 16:01 UTC, kelson42 commented
@gouri-panda Here too we need a new review pass. PR is mandatory for 3.8 and we want to release.

2023-10-14 18:04 UTC, kelson42 commented
@MohitMaliFtechiz Can you please rebase and fix conflicts?
@gouri-panda we really need your review! Waiting for weeks creates a significant overhead for Mothit.

2023-10-20 11:03 UTC, kelson42 commented
@MohitMaliFtechiz Why this PR is in draft?

2023-10-20 11:22 UTC, MohitMaliFtechiz commented
@kelson42 TestCases have failed on API level 31 twice after merging a PR, that's why I have marked this PR as draft. I have not tested this PR yet why the test cases are falling after merging another PR.

2023-10-20 11:25 UTC, kelson42 commented
@MohitMaliFtechiz OK, please complete once current issues around custom apps are fixed

2023-10-27 14:01 UTC, MohitMaliFtechiz commented
@kelson42, @gouri-panda Test cases are fixed, now this PR is ready for review.

2023-11-11 07:49 UTC, kelson42 commented
@gouri-panda Any update?

2023-11-12 17:00 UTC, kelson42 commented
Merging... without review :(

2023-11-12 17:00 UTC, merged

2023-11-12 18:15 UTC, gouri-panda reviewed
@MohitMaliFtechiz Looks good to me! Thanks for the tests. I can't produce the error that i was talking about. Unfortunately, i can't find the commit that fixed.

2023-11-16 06:20 UTC, MohitMaliFtechiz commented
>  Unfortunately, i can't find the commit that fixed.

@gouri-panda The issue was on the server side, after adapting the latest `java-libkiwix` that issue was automatically resolved.

2023-11-16 08:15 UTC, gouri-panda commented
@MohitMaliFtechiz Ok. Thanks!