Refactor GitHub Action for Emulator Runner Job Redundancy
kiwix/kiwix-android pull request #3616
Opened 2023-12-17 18:21 UTC by gouri-panda

Fixes #3615 

**Description**
This pull request addresses the redundancy in the GitHub Actions workflow for creating instrumentation coverage with the Android Emulator Runner. The current workflow contains duplicated code, and this PR refactors it into a single job definition with conditional parameter assignments based on the value of matrix.api-level.

2023-12-18 11:36 UTC, MohitMaliFtechiz commented on .github/workflows/ci.yml
> +         ram-size: ${{ matrix.api-level != 33 && '4096M' || '4096M' }}
@gouri-panda Since `ram-size` is the same for both API levels, we should get rid of this condition here.

2023-12-18 11:39 UTC, MohitMaliFtechiz requested changes
@gouri-panda Thanks for the PR, just need a small change, and then we are good to merge.

2023-12-18 13:48 UTC, MohitMaliFtechiz approved these changes
@gouri-panda Thanks LGTM, once CI paas we can merge.

2023-12-19 03:46 UTC, kelson42 requested changes
Indentation is incorrect

2023-12-21 20:00 UTC, gouri-panda commented
@kelson42 Thanks!

2023-12-22 06:44 UTC, MohitMaliFtechiz approved these changes
@gouri-panda Thanks.

2023-12-22 07:29 UTC, merged