Upgraded `webkit` version to latest to work with latest `chromium` dependencies.
kiwix/kiwix-android pull request #3648
Opened 2024-01-02 11:40 UTC by MohitMaliFtechiz

Fixes #3644 

* Upgraded the `WebKit` version to the latest (from 1.3.0 to 1.7.0) to leverage improvements and bug fixes. This update is essential to address the issue with the latest `chromium` dependency, as outlined in #3644.
* Additionally, elevated the `androidx.annotation:annotation` dependency from `1.1.0` to `1.2.0` to meet the requirements of the updated WebKit version.

2024-01-02 15:14 UTC, gouri-panda requested changes
@MohitMaliFtechiz We need to change the parameters of the  new API.

2024-01-02 15:59 UTC, MohitMaliFtechiz commented
@gouri-panda Which new API? Are you talking about to update all the dependencies according to our compiled SDK version?

2024-01-02 16:11 UTC, gouri-panda commented
@MohitMaliFtechiz For some reason the string files doesn't compile to the recent versions even though we haven't changed here. So I guess the new SDK cause there.
```
 /home/runner/work/kiwix-android/kiwix-android/core/src/main/res/values-zh-rTW/strings.xml:303: Conflicting number of arguments (0) here
```

2024-01-02 16:16 UTC, MohitMaliFtechiz commented
@gouri-panda Now I got your point.

No, it is not related to the new SDK, We have implemented https://github.com/kiwix/kiwix-android/issues/3625 after that this error came. I already placed a fix for it on `translate wiki` and some of the strings have already come in the latest translateWiki PR only 2 translations are left to come. Once all the changes are come these errors will automatically gone.

2024-01-02 19:33 UTC, kelson42 commented
@MohitMaliFtechiz Do zimit still work properly?

2024-01-03 09:03 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz Do zimit still work properly? It does not i play to stop supporting older versions of Android?

@kelson42 Yes it is working with Zimit files, I have tested it on Android 8, Android 12, and Android 13.

**On Android 8**

![Screenshot_20211214-143511](https://github.com/kiwix/kiwix-android/assets/34593983/11251224-674e-404f-a725-dd2fcb6013f6)

**On Android 12**

https://github.com/kiwix/kiwix-android/assets/34593983/0454f8a3-d542-4268-a8f1-5e4a549bc569

2024-01-03 10:15 UTC, merged