Fix bottom page content being cut
kiwix/kiwix-android pull request #3977
Opened 2024-08-13 13:50 UTC by CalebKL

Fixes #https://github.com/kiwix/kiwix-android/issues/3964

This PR fixes the bottom page being cut when scrolling up and down. Since the zimfile content being fetched is already wrapped with a specific color, adding a big padding will make the color scheme inconsistent. I have tested with 40dp and it seems to work well from my device and emulator.

2024-08-13 16:40 UTC, kelson42 commented
@CalebKL Thank you very much for this PR!

2024-08-14 10:43 UTC, MohitMaliFtechiz requested changes
@CalebKL This solution is working correctly in the normal mode. But in the "full screen" mode the padding of the bottom cuts the content until the user fully scrolls down the webView, and this is looking weird.


https://github.com/user-attachments/assets/1a299124-acab-48ab-99f1-78acd1c90a4b

2024-08-14 12:14 UTC, CalebKL commented
> @CalebKL This solution is working correctly in the normal mode. But in the "full screen" mode the padding of the bottom cuts the content until the user fully scrolls down the webView, and this is looking weird.
> 
>  XRecorder_14082024_160709.mp4

Fixed this with the latest commits

2024-08-16 10:58 UTC, kelson42 commented
@MohitMaliFtechiz Good to merge?

2024-08-16 12:50 UTC, MohitMaliFtechiz approved these changes
@CalebKL Thanks for the new changes, it is working as expected. @kelson42 LGTM. Once CI is passed we can merge this.

2024-08-16 15:34 UTC, merged