Migrate totalSpace to IO Thread
kiwix/kiwix-android pull request #4061
Opened 2024-11-07 06:17 UTC by CalebKL

Fixes #4038 

This PR, moves `totalSpace` to the IO Thread and removes runBlocking which was blocking the main thread. 

**Screenshots**

2024-11-11 21:13 UTC, kelson42 commented
@CalebKL Ready to review?

2024-11-12 10:21 UTC, CalebKL commented
> @CalebKL Ready to review?

Yes. I have already talked to  @MohitMaliFtechiz. 
I will proceed with the other tasks from 4035](https://github.com/kiwix/kiwix-android/issues/4035). 
@MohitMaliFtechiz I had accidentally committed the old and new string(tarask) thats why I had to roll back and force-push without the strings. 
Apart from that, the PR is a go for review.

2024-11-12 12:27 UTC, MohitMaliFtechiz commented
@CalebKL Thanks, i will review it soon.

2024-12-04 11:59 UTC, MohitMaliFtechiz requested changes
@CalebKL Please rebase, and resolve the conflicts, and see the review comments.

2024-12-04 11:59 UTC, MohitMaliFtechiz commented on app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToRoomMigratorTest.kt
> +  private val migrationMaxTime = 100000
Why we are increasing this timeout?

2024-12-05 13:28 UTC, MohitMaliFtechiz commented
@CalebKL Please resolve the conflicts by rebasing the PR. There are some conflicts due to merge commits.

![Screenshot from 2024-12-05 18-58-20](https://github.com/user-attachments/assets/5347f230-3652-45c4-9f55-37bdd81da35d)

2024-12-06 05:12 UTC, MohitMaliFtechiz approved these changes

2024-12-08 07:45 UTC, merged