#4083 fixed external link warning when user wants to make a donation
kiwix/kiwix-android pull request #4133
Opened 2024-12-10 19:25 UTC by viditpawar0

Fixes #4083 

Fixed external link warning when user wants to make a donation

2024-12-11 12:25 UTC, MohitMaliFtechiz requested changes
@viditpawar0 We have the `DonationPopup` functionality as well which we have recently added, which shows on the reader screen. So when the user clicks on the "Make a donation" button this method calls https://github.com/kiwix/kiwix-android/blob/9fc6e66ecc00ddcc6b93e958934ff3f2ccbbaa8b/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt#L1676

According to your existing code, it will work fine with the Kiwix app, but for custom apps, we have overrided this method in  `CustomReaderFragment` to make custom behavior according to configuration. So we have to make the changes there as well so that when while user clicks on the donation button in custom apps this popup will not show.


Apart from these changes: The test cases are falling due to this change specially `topLevelDestinationTest` so can you please fix that?

2024-12-11 12:25 UTC, MohitMaliFtechiz commented on core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
> +    externalLinkOpener.openExternalUrl(KIWIX_SUPPORT_URL.toUri().browserIntent(), false)
@viditpawar0 We have the same functionality for custom apps as well. So in `CustomMainActivity` we have a function `openExternalUrl`. With this function, we are opening the `support_url` which is the same as the Kiwix app so we should refactor the code there as well.

2024-12-11 15:10 UTC, viditpawar0 commented
Sure, I'll do that

2024-12-11 17:32 UTC, viditpawar0 commented
Done

2024-12-11 18:36 UTC, viditpawar0 commented
All the requested changes have been done.

Summary: -
- made the same fix for custom apps in `CustomMainActivity`
- modified `topLevelDestinationTest`
- fixed the same for `CoreReaderFragment` and `CustomReaderFragment`

2024-12-12 06:02 UTC, MohitMaliFtechiz requested changes
@viditpawar0 Thanks for making the changes. Please see comments.

2024-12-12 09:49 UTC, viditpawar0 commented
Okay, made the required changes

2024-12-12 12:27 UTC, MohitMaliFtechiz approved these changes
@viditpawar0 Thanks for making the changes. @kelson42 LGTM.

2024-12-12 12:38 UTC, merged